language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: whalenut-github


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
